import OpenAI from 'openai';
import logger from '../utils/logger';
import { getOptionSuggestionPrompt, getSimpleAdvicePrompt, getMarketBriefingPrompt } from '../utils/prompts';
import { IOptionInsight } from './gemini.service'; // Re-use the interface

let openai: OpenAI | null = null;

const getOpenAIClient = (): OpenAI => {
    if (!openai) {
        try {
            openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY || 'dummy_key_for_build' });
        } catch (err) {
            logger.error('Failed to initialize OpenAI SDK', { error: err });
            throw new Error('OpenAI SDK initialization failed');
        }
    }
    return openai;
};

function getFormattedDate() {
    return new Date()
        .toLocaleDateString('en-US', { month: 'short', day: '2-digit', year: 'numeric' })
        .replace(',', '')
        .replace(/\s/g, '-');
}

export const generateOptionSuggestionChatGPT = async (ticker: string): Promise<IOptionInsight> => {
    const t0 = Date.now();
    const client = getOpenAIClient();
    const prompt = getOptionSuggestionPrompt(ticker, getFormattedDate());

    try {
        const response = await client.chat.completions.create({
            model: "gpt-4o",
            messages: [{ role: "user", content: prompt }],
            response_format: { type: "json_object" }
        });

        const duration = Date.now() - t0;

        logger.info('ChatGPT AI Generation Success', {
            ticker,
            durationMs: duration
        });

        const textOutput = response.choices[0].message.content || "{}";
        const jData = JSON.parse(textOutput);

        if (!jData.action || !jData.confidence) {
            throw new Error('AI returned malformed JSON structure');
        }

        return {
            action: jData.action,
            confidence: jData.confidence,
            risk: jData.risk || 'Unknown',
            support: jData.support || 0,
            resistance: jData.resistance || 0,
            pe: jData.pe || 0,
            industryPe: jData.industryPe || 0,
            averagePe5Yr: jData.averagePe5Yr || 0,
            forecast1Year: jData.forecast1Year || { text: 'Unknown', color: 'yellow' },
            tomorrowRange: jData.tomorrowRange || 'Unknown',
            emaAnalysis: jData.emaAnalysis || { text: 'Unknown', color: 'yellow' },
            rsiAnalysis: jData.rsiAnalysis || { text: 'Unknown', color: 'yellow' },
            vixThetaAnalysis: jData.vixThetaAnalysis || { text: 'Unknown', color: 'yellow' },
            supportResistanceAnalysis: jData.supportResistanceAnalysis || 'Unknown',
            verdict: jData.verdict || { text: 'Unknown', color: 'yellow' },
            trend: jData.trend || 'Unknown',
            newsSummary: jData.newsSummary || { text: 'No recent news available.', color: 'yellow' },
            analysis: jData.analysis || { text: 'No recent analysis available.', color: 'yellow' }
        };

    } catch (error: any) {
        const duration = Date.now() - t0;
        logger.error('ChatGPT AI Generation Failed', {
            ticker,
            durationMs: duration,
            error: error.message
        });

        if (error.message?.includes('429')) {
            throw new Error('ChatGPT API Rate Limit Reached.');
        }

        throw new Error('Failed to generate option analysis via ChatGPT');
    }
};

export const generateSimpleAdviceChatGPT = async (ticker: string): Promise<string> => {
    const t0 = Date.now();
    const client = getOpenAIClient();
    const prompt = getSimpleAdvicePrompt(ticker, getFormattedDate());

    try {
        const response = await client.chat.completions.create({
            model: "gpt-4o",
            messages: [{ role: "user", content: prompt }]
        });

        logger.info('ChatGPT AI Simple Advice Success', {
            ticker,
            durationMs: Date.now() - t0
        });

        return response.choices[0].message.content || "No advice generated by ChatGPT.";
    } catch (error: any) {
        logger.error('ChatGPT AI Simple Advice Failed', {
            ticker,
            durationMs: Date.now() - t0,
            error: error.message
        });

        if (error.message?.includes('429')) {
            throw new Error('ChatGPT API Rate Limit Reached.');
        }

        throw new Error('Failed to generate simple advice via ChatGPT');
    }
};

export const generateMarketBriefingChatGPT = async (): Promise<string> => {
    const t0 = Date.now();
    const client = getOpenAIClient();
    const prompt = getMarketBriefingPrompt(getFormattedDate());

    try {
        const response = await client.chat.completions.create({
            model: "gpt-4o",
            messages: [{ role: "user", content: prompt }]
        });

        logger.info('ChatGPT AI Market Briefing Success', {
            durationMs: Date.now() - t0
        });

        let textOutput = response.choices[0].message.content || "<div>No briefing generated by ChatGPT.</div>";
        textOutput = textOutput.replace(/```html\n?/g, '').replace(/```\n?/g, '');
        return textOutput;
    } catch (error: any) {
        logger.error('ChatGPT AI Market Briefing Failed', {
            durationMs: Date.now() - t0,
            error: error.message
        });

        if (error.message?.includes('429')) {
            throw new Error('ChatGPT API Rate Limit Reached.');
        }

        throw new Error('Failed to generate market briefing via ChatGPT');
    }
};
